locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: card
    locators:
      - mode: text
        value: Debit Card
        index: 0
        uses: 24
  - verb: fill
    name: card
    locators:
      - mode: css
        value: '[maxlength="30"]'
        index: 0
        uses: 5
  - verb: click
    name: verify_card
    locators:
      - mode: text
        value: Verify card
        index: 0
        uses: 12
  - verb: click
    name: use_this_payment_method
    locators:
      - mode: value
        value: Use this payment method
        index: 0
        uses: 18
  - verb: type
    name: tab
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: place_your_order
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Place Your Order
        index: 0
        uses: -1
      - mode: text
        value: Place your order
        index: 0
        uses: -1
      - mode: text
        value: place your order
        index: 0
        uses: -1
      - mode: value
        value: Place Your Order
        index: 0
        uses: -1
      - mode: value
        value: Place your order
        index: 0
        uses: -1
      - mode: value
        value: place your order
        index: 0
        uses: -1
