language: python
python:
  - 3.9

before_install:
  - curl -sSL https://install.python-poetry.org | python3 -

install:
  - make install

script:
  - make ci

notifications:
  email:
    on_success: never
    on_failure: never
