[tool.poetry]

name = "amazon"
version = "0.1"
description = "Reload your Amazon balance automatically."
authors = ["Jace Browning <jacebrowning@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]

python = "^3.7"

pomace = "=0.3b6"

[tool.poetry.dev-dependencies]

black = {version = "^19.10b0", allow-prereleases = true}

[tool.poetry.scripts]

reload-amazon-balance = 'amazon:cli'

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
