[tool.poetry]

name = "amazon"
version = "0.0"
description = ""
authors = ["Jace Browning <jacebrowning@gmail.com>"]

[tool.poetry.dependencies]

python = "^3.7"

pomace = "=0.0.2"

[tool.poetry.dev-dependencies]

black = {version = "^19.10b0", allow-prereleases = true}

[tool.poetry.scripts]

reload-amazon-balance = 'amazon:reload_balance'

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
