actions:
  - verb: click
    name: reload_again
    locators:
      - mode: partial_text
        value: Reload your balance again
        index: 0
        score: 0.7450580596923828
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.0
active_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.0
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.0
