actions:
  - verb: click
    name: reload_again
    locators:
      - mode: text (partial)
        value: Reload your balance again
        index: 0
        uses: 48
      - mode: text
        value: Reload Again
        index: 0
        uses: 0
      - mode: text
        value: Reload again
        index: 0
        uses: 0
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
locators:
  inclusions:
    -
  exclusions:
    -
