locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: password
    locators:
      - mode: name
        value: password
        index: 0
        uses: 2
  - verb: click
    name: sign_in
    locators:
      - mode: id
        value: signInSubmit
        index: 0
        uses: 2
