actions:
  - verb: click
    name: not_now
    locators:
      - mode: id
        value: ap-account-fixup-phone-skip-link
        index: 0
        uses: 3
locators:
  inclusions:
    -
  exclusions:
    -
