locators:
  inclusions:
    -
  exclusions:
    -
actions:
  - verb: fill
    name: amount
    locators:
      - mode: id
        value: gc-ui-form-custom-amount
        index: 0
        uses: 2
  - verb: click
    name: buy_now
    locators:
      - mode: id
        value: gcui-asv-reload-buynow-button
        index: 0
        uses: 24
  - verb: click
    name: sign_in
    locators:
      - mode: text
        value: Sign in
        index: 1
        uses: 1
      - mode: id
        value: nav-link-accountList-nav-line-1
        index: 0
        uses: 2
  - verb: type
    name: tab
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: one_time_reload
    locators:
      - mode: text
        value: One Time Reload
        index: 1
        uses: 2
