locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: amount
    locators:
      - mode: id
        value: gcui-asv-reload-form-custom-amount
        index: 0
        uses: 26
  - verb: type
    name: tab
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: buy_now
    locators:
      - mode: id
        value: gcui-asv-reload-buynow-button
        index: 0
        uses: 25
  - verb: click
    name: sign_in
    locators:
      - mode: text
        value: Sign in
        index: 1
        uses: 14
