actions:
  - verb: click
    name: reload_again
    locators:
      - mode: partial_text
        value: Reload your balance again
        uses: 0
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        uses: 0
active_locators:
  - mode: ''
    value: ''
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    uses: 0
